// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibgqfiufkfuixdavotmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZ3FmaXVma2Z1aXhkYXZvdG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTgxMTIsImV4cCI6MjA3MDc3NDExMn0.zRWm-y1CSEa_xq84xyL858DLZ6jkdc8RX3skbEgVkZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});